### PR TITLE
Racktables importer

### LINKED ISSUE #21: racktables importer
We should be able to import all data from Racktables in order to be a viable alternative

### PR DESCRIPTION
**Pull request by akosiaris**
Add a racktables to hwdoc import script. For now only mysql support
exists and we target version 0.20.4. Various assumptions had to be made
to make this possible. Unfortunately racktables and servermon vary quite
a lot in the way they structure their models and relations. It might
need updates depending on installation. We are obviously gonna accept
PRs though.

This closes #21

### CODE REVIEW

**Comment by Krenair** [comment]
I haven't got this to succeed a full run yet. Notes so far:
* MySQL user and password should be considered required
* If a row's location is None, yell about it in console instead of skipping the row and breaking when we try to get the RackRow object later
* I don't seem to have any RackModel objects, so it breaks at line 123 "rm = RackModel.objects.get(id=1)"

**Comment by akosiaris** [comment]
>  * MySQL user and password should be considered required

Done. Both indicated in the help messages and enforced in the code

> * If a row's location is None, yell about it in console instead of skipping the row and breaking when we try to get the RackRow object later

The way I read the code, it does not break, it just skips the RackRow if it's localtion is `None`, printing 
```
RackRow does not exist: <rackrow_name>. Skipping rack <rack_name>
```

Am I missing something ? 

> * I don't seem to have any RackModel objects, so it breaks at line 123 "rm = RackModel.objects.get(id=1)"

Yeah, that line I hate.. unfortunately racktables does not have the concept of rack models at all. Anyway, it's fixable. You probably haven't loaded vendor-model fixtures.

./manage.py loaddata vendor-model

**Comment by Krenair** [comment]
> The way I read the code, it does not break, it just skips the RackRow if it's localtion is None, printing
> RackRow does not exist: <rackrow_name>. Skipping rack <rack_name>
> Am I missing something ?

No but I think it should be made explicit when you skip the row, it happened because the location was None.

> Yeah, that line I hate.. unfortunately racktables does not have the concept of rack models at all. Anyway, it's fixable. You probably haven't loaded vendor-model fixtures.
> ./manage.py loaddata vendor-model

Haven't tested, but let's print that and exit if there are no RackModels?

**Comment by Krenair** [comment]
It ran successfully after "./manage.py loaddata vendor-model", I'll amend with a couple of print()s and see what needs to be added to complete this later. IIRC you said that support for PDUs needed to be added, among other things?

**Comment by akosiaris** [comment]
> The way I read the code, it does not break, it just skips the RackRow if it's localtion is None, printing
RackRow does not exist: . Skipping rack 
Am I missing something ?
No but I think it should be made explicit when you skip the row, it happened because the location was None.

Indeed. I 've added a print to show that a row is skipped if it does not have a location and amended the above message to indicate it as well.

For what is worth, we probably want that information as well migrated, not sure yet how and where to store it.

> Yeah, that line I hate.. unfortunately racktables does not have the concept of rack models at all. Anyway, it's fixable. You probably haven't loaded vendor-model fixtures.
./manage.py loaddata vendor-model
Haven't tested, but let's print that and exit if there are no RackModels?

Agreed. Done.

**Comment by akosiaris** [comment]
Yes, PDUs are kind of strangely stored in racktables. Some are zero U, some are not (depending on the initial version and upgrades since then), but most importantly don't have a clear equipment model and hence are skipped.

**Comment by Krenair** [comment]
I noticed that the object select queries effectively exclude objects without any attributes set, even if they have type server etc.

**Comment by akosiaris** [comment]
Quite possibly, I suppose some JOIN needs to be converted into a LEFT JOIN. I 'll look into it.

**Comment by Krenair** [comment]
I should probably be the one updating this pull request at the moment, don't worry about it for now :)

**Comment by Krenair** [comment]
I tried creating PDUs and they got imported successfully :/

**Comment by Krenair** [comment]
Is there a way to query wikimedia production racktables for entries with no HW type or OEM S/N 1 without having direct MySQL access?

**Comment by Krenair** [comment]
Okay, so I've been looking through the Wikimedia DB and those PDUs don't have HW types.

**Comment by akosiaris** [comment]
Yeah, that's true. I have been thinking about adding a new hw type to
racktables and move those PDUs to that first. How does that sound?
Στις 16 Ιουν 2016 19:30, ο χρήστης "Alex Monk" <notifications@github.com>
έγραψε:

**Comment by Krenair** [comment]
We found other non-PDU objects with missing HW type or OEM S/N 1 attributes.
I'm wondering if we can make a generic "Unknown" HW type.

**Comment by akosiaris** [comment]
Merging as is and will work more on it if required

**Pull request merged**
